### ISSUE TITLE
sql issue with latest download. Any ideas as to problem below. 

### ISSUE THREAD

**Issue by thecount12** [nopri/onlinestore-multi#1]
return process(self.processors)
[Fri Feb 08 11:38:06 2013] [error] [client 67.217.144.187]   File "/usr/lib/pymodules/python2.6/web/application.py", line 249, in process
[Fri Feb 08 11:38:06 2013] [error] [client 67.217.144.187]     raise self.internalerror()
[Fri Feb 08 11:38:06 2013] [error] [client 67.217.144.187]   File "/var/www/online/onlinestore-multi-master/app.py", line 1913, in internalerror
[Fri Feb 08 11:38:06 2013] [error] [client 67.217.144.187]     expose_error = pget('expose_error')
[Fri Feb 08 11:38:06 2013] [error] [client 67.217.144.187]   File "/var/www/online/onlinestore-multi-master/app.py", line 220, in pget
[Fri Feb 08 11:38:06 2013] [error] [client 67.217.144.187]     r = query(q, a)
[Fri Feb 08 11:38:06 2013] [error] [client 67.217.144.187]   File "/var/www/online/onlinestore-multi-master/app.py", line 186, in query
[Fri Feb 08 11:38:06 2013] [error] [client 67.217.144.187]     r = db.query(q, vars = a)
[Fri Feb 08 11:38:06 2013] [error] [client 67.217.144.187] AttributeError: 'NoneType' object has no attribute 'query'

**Comment by ProfessionalIT** [comment]
where this project is running in production ?

**Comment by nopri** [comment]
Hello,

I apologize for the very delayed response. I did not receive notification because i was not watching this repository. And, thank you very much for your interest in this application. 

Although probably this reply is no longer needed or relevant: 

@thecount12,  this application switched to SQLite database in 2013-December. There were some updates to the code (along with bug fixes) during the database switch. 

@ProfessionalIT, as of today, i don't know where this project is running in production. 

Also, please note that there will be no new features added to this application (only bug fixes). 

Thank you.
nop
